# Generated by Django 4.2.7 on 2023-11-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
                ('dname', models.CharField(max_length=50)),
                ('eprice', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
