# Generated by Django 4.2.7 on 2023-11-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_destination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Destinations',
        ),
    ]
