# Generated by Django 4.2.7 on 2023-11-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_destination_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidayreserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('no_of_adults', models.PositiveIntegerField()),
                ('no_of_children', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
