# Generated by Django 4.2.7 on 2023-11-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_holidayreserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayreserve',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='holidayreserve',
            name='updated_at',
        ),
    ]
