# Generated by Django 4.2.7 on 2023-11-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_holidayreserve_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayreserve',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='holidayreserve',
            name='children_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='holidayreserve',
            name='destination',
            field=models.CharField(default='Maasai Mara', max_length=100),
        ),
    ]
