# Generated by Django 4.2.7 on 2023-12-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_holidayreserve_adult_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayreserve',
            name='adult_price',
        ),
        migrations.RemoveField(
            model_name='holidayreserve',
            name='children_price',
        ),
        migrations.AddField(
            model_name='holidayreserve',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
