from django.contrib import admin
from django.urls import path
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landingpage, name='landingpage'),
    path('index/', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('Booking/', views.book, name='book'),
    path('Tzsafaris/', views.tzsafaris, name='tzsafaris'),
    path('kesafaris/', views.kesafaris, name='kesafaris'),
    path('Ugsafaris/', views.Ugsafaris, name='Ugsafaris'),
    path('Rwsafaris/', views.Rwsafaris, name='Rwsafaris'),
    path('testimonials/', views.testimonials, name='testimonials'),
    path('proposal/', views.proposal, name='proposal'),
    path('success/', views.success, name='success'),
    path('stk/', views.stk, name='stk'),
    path('token/', views.token, name='token'),
    path('pay/', views.stk, name='pay'),
    path('newyeardeals/', views.nyd, name='nyd'),
    path('valentines/', views.vln, name='vln'),
    path('easter/', views.est, name='est'),
    path('labor/', views.lbd, name='lbd'),
    path('madaraka/', views.mad, name='mad'),
    path('huduma/', views.hud, name='hud'),
    path('mashujaa/', views.mash, name='mash'),
    path('christmas/', views.xmas, name='xmas'),
    path('jamhuri/', views.jam, name='jam'),
    path('delete/<int:id>', views.delete),
    path('edit/<int:id>', views.edit),
    path('payment_page/', views.payment_page, name='payment_page'),
    path('holiday-detailsmhk1/', views.hdl1, name='hdl1'),
    path('holiday-detailsmhk2/', views.hdl2, name='hdl2'),
    path('holiday-detailsmhk3/', views.hdl3, name='hdl3'),
    path('holiday-detailssb1/', views.hdl4, name='hdl4'),
    path('holiday-detailssb2/', views.hdl5, name='hdl5'),
    path('holiday-detailssb3/', views.hdl6, name='hdl6'),
    path('holiday-detailswld1/', views.hdl7, name='hdl7'),
    path('holiday-detailswld2/', views.hdl8, name='hdl8'),
    path('holiday-detailswld3/', views.hdl9, name='hdl9'),
    path('show/', views.show, name='show'),
    path('rsv1/', views.rsv1, name='rsv1'),
    path('rsv2/', views.rsv2, name='rsv2'),
    path('rsv3/', views.rsv3, name='rsv3'),
    path('services/', views.services, name='services'),
]
